### ISSUE TITLE
View our Solution - loading

### ISSUE THREAD

**Issue by jermyk** [neontribe/www#222] opened 2019-07-02 15:03 UTC
When the page loads the user is take to the solution of the story from the homepage. In this instance ARC.

The page loads but the user doesn't see the story for Allegiant as the ARC story is half way down the page, and the user (if they didn't scroll up) would miss the Allegiant story.

**Comment by RpprRoger** [comment] 2019-07-02 15:22
This is a feature, we want to take people directly to the solution for that story.

**Comment by RpprRoger** [comment] 2019-07-02 15:29
Perhaps we should re-order them to have the linked one at the top?

**Comment by katjam** [comment] 2019-07-03 08:10
Following paper prototype testing - we removed that feature from the home page - due to evidence it was confusing and/or ignored. I wonder if the easiest solution for now is to go back to that plan?

**Comment by katjam** [comment] 2019-08-27 10:48
Closing - behaviour as designed. We might find a user need for this during testing in future.

**Closed by katjam** 2019-08-27 10:48 UTC
Labels: Improvement, Research
