### ISSUE TITLE
Mobile nav buttons

### ISSUE THREAD

**Issue by Nikomus** [neontribe/www#314] opened 2019-10-01 15:37 UTC
Split from #230

Red box appears around nav buttons when active
![Screenshot_070319_011545_PM](https://user-images.githubusercontent.com/4446325/60590770-c3f75e00-9d94-11e9-9256-023760145198.jpg)

## Plan
- [ ] 

## Acceptance Criteria
- [ ]

**Comment by falconx** [comment] 2019-10-28 11:18
I thought this was expected? Since the active/focus styles take from the colour array and it happens that this colour next in line.

**Comment by Nikomus** [comment] 2019-10-31 12:37
@falconx I think this is reporting that the active state "sticks". The border stays after the button is released.

In the picture the border also looks too thin compared to other places but I can't reproduce that now.

**Comment by falconx** [comment] 2019-11-01 15:44
@Nikomus I'm not sure how this is different behaviour from anything else? :thinking: once the focus is set elsewhere, the focus style is removed here, at least in my testing. would it be possible to add a video or step by step instructions on how to reproduce this?

**Comment by SarikaWirtz** [comment] 2019-11-06 09:23
@Nikomus @falconx  i tested this in real device iPhoneX and it looks perfectly okay but in old android samsung s5 it's the same as your attached picture.

**Comment by katquatermass** [comment] 2020-01-21 11:44
This needs a decision on whether it should be fixed or not. In the new world it would not have got to this column without that decision. So moving to backlog (top of) so it is among the first to get a documented decision made.

**Comment by katjam** [comment] 2020-01-21 14:07
@Nikomus I agree with @falconx this is expected behaviour. Can we close?

**Comment by katjam** [comment] 2020-10-14 10:57
Closing as no longer an issue with new design. We want the button to stay focused when clicked

**Closed by katjam** 2020-10-14 10:57 UTC
Labels: Bug, Code/ Dev Backlog
